### ISSUE TITLE
Tornar opção "Ver funções disponíveis" fixa

### ISSUE THREAD

**Issue by clemilsonmorais** [lar-ect/plataforma-lop#26]
Ao clicar no botão "Ver funções disponíveis", a lista com as funções poderia ser uma tabela fixa, para facilitar a consulta durante a criação do código.

**Comment by tibuurcio** [comment]
Gosto da ideia. No caso a tabela seria aberta em um modal né?

**Comment by clemilsonmorais** [comment]
Talvez até em um elemento fixo na página mesmo, pra não ter que ficar abrindo e fechando direto

**Comment by tibuurcio** [comment]
Um usuário fez essa sugestão para o sistema. Vou marcar como urgente porque estou vendo demanda por isso.
