### ISSUE TITLE
Implementar uma rotina de teste de execução de todas as questões do sistema utilizando seus códigos de solução como resposta

### ISSUE THREAD

**Issue by tibuurcio** [lar-ect/plataforma-lop#41]
Sempre que for necessário mudar alguma lógica na execução de código do sistema, é necessário testar se todas as questões estão executando de forma correta para que não hajam problemas futuros.

Essa issue depende de #17 para que os códigos de solução das questões possam ser cadastrados.

O que acha disso @orivaldosantana ?

**Comment by orivaldosantana** [comment]
Essencial para a manutenção do sistema.
