### ISSUE TITLE
Alterar intervalo de dificuldades possíveis no cadastro de questões

### ISSUE THREAD

**Issue by tibuurcio** [lar-ect/plataforma-lop#8]
O cadastro pode ser visualizado em http://plataforma-lop.ddns.net/questao/adicionar

Atualmente no cadastro de questão, pode-se escolher a dificuldade da questão que está sendo cadastrada como um valor entre 1 e 10. Essa variação não é significativa pois a diferença entre uma questão de dificuldade 8 para 9 não trás muito peso a quem vai resolver.

@alvaropfn Sugeriu utilizar a escala de fibonacci, acho uma boa ideia.

Também acho que definir como fácil, médio e difícil, ou básico, intermediário e avançado sejam boas ideias.

Pensamentos? @orivaldosantana

**Comment by orivaldosantana** [comment]
Na hora de preparar uma lista ou uma prova é interessante saber o nível de dificuldade. A forma mais comum de expressar o nível de dificuldade é fácil, médio e difícil. Para deixar com mais opções podemos usar: muito fácil, fácil, médio, difícil e muito difícil. Essa é a minha sugestão :)
